using System.Text.Json.Nodes;
using HostsManager.Core;

namespace HostsManager.Tests;

public sealed class BrowserPreviewAppearanceTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "preview-color-" + Guid.NewGuid());
    private BrowserPreviewProfiles Store => new(_root);
    private BrowserPreviewProfile Create()
    {
        var path = Path.Combine(_root, "chrome", "abcdef123456");
        Directory.CreateDirectory(path);
        return new("chrome", "abcdef123456", path);
    }

    [Theory]
    [InlineData("chrome", "autogenerated_theme_id")]
    [InlineData("edge", "autogenerated_theme_id")]
    public void ColorUpdatesOnlyThemePreservingOtherSettings(string browser, string themeId)
    {
        var json = new BrowserPreviewAppearance("Staging", "#ff0000")
            .UpdatePreferences("{\"session\":{\"restore_on_startup\":1},\"browser\":{\"other\":true}}", browser);
        var result = JsonNode.Parse(json)!;
        Assert.Equal(1, (int)result["session"]!["restore_on_startup"]!);
        Assert.True((bool)result["browser"]!["other"]!);
        Assert.Equal(themeId, (string?)result["extensions"]!["theme"]!["id"]);
        var color = result["autogenerated"]!["theme"]!["color"];
        Assert.Equal(-65536, (int)color!);
        Assert.False((bool)result["browser"]!["theme"]!["is_grayscale2"]!);
        Assert.False((bool)result["browser"]!["theme"]!["follows_system_colors"]!);
        Assert.Null(result["browser"]!["theme"]!["user_color2"]);
    }

    [Fact]
    public void ReturningToDefaultRemovesGeneratedColor()
    {
        var colored = new BrowserPreviewAppearance(null, "#2563EB").UpdatePreferences("{}", "chrome");
        var result = JsonNode.Parse(new BrowserPreviewAppearance(null, null).UpdatePreferences(colored, "chrome"))!;
        Assert.Null(result["browser"]!["theme"]!["user_color2"]);
        Assert.Null(result["autogenerated"]!["theme"]!["color"]);
        Assert.Equal("", (string?)result["extensions"]!["theme"]!["id"]);
    }

    [Theory]
    [InlineData("red")]
    [InlineData("#123")]
    [InlineData("#12345678")]
    public void InvalidColorIsRejected(string color) =>
        Assert.Throws<ArgumentException>(() => new BrowserPreviewAppearance(null, color).Normalize());

    [Fact]
    public void AppearanceSurvivesLaunchMetadataAndLegacyProfilesCanBeNamed()
    {
        var profile = Create();
        Store.SaveAppearance(profile, new(" Staging ", "#2563eb"), _ => true); // New profile has never been opened.
        Store.RecordLaunch(profile, ["api.test → 127.0.0.1"], []);
        var updated = Assert.Single(Store.List());
        Assert.Equal("Staging", updated.Metadata!.Name);
        Assert.Equal("#2563EB", updated.Metadata.Color);
        Assert.Contains("api.test", updated.DisplayName);
        Store.SaveAppearance(updated, new("Renamed", "#2563EB"), _ => true); // Name-only edits do not touch browser prefs.
        Assert.Equal("Renamed", Assert.Single(Store.List()).Metadata!.Name);
    }

    [Fact]
    public void RunningBrowserRefusesExistingProfileColorChangeWithoutMutation()
    {
        var profile = Create();
        Store.SaveAppearance(profile, new("Blue", "#2563EB"), _ => false);
        var file = Path.Combine(profile.Path, "Default", "Preferences");
        var before = File.ReadAllText(file);
        Assert.Throws<InvalidOperationException>(() => Store.SaveAppearance(profile, new("Red", "#FF0000"), _ => true));
        Assert.Equal(before, File.ReadAllText(file));
        Assert.Equal("Blue", Assert.Single(Store.List()).Metadata!.Name);
    }

    [Fact]
    public void ExistingColorMigratesToGeneratedThemeWithoutChangingIdentity()
    {
        var profile = Create();
        File.WriteAllText(Path.Combine(profile.Path, "hostsmanager-preview.json"),
            "{\"Mappings\":[],\"Flags\":[],\"LastLaunchedUtc\":\"2026-09-24T00:00:00Z\",\"Color\":\"#DB2777\"}");
        Store.SaveAppearance(profile, new(null, "#DB2777"), _ => false);
        var prefs = JsonNode.Parse(File.ReadAllText(Path.Combine(profile.Path, "Default", "Preferences")))!;
        Assert.Equal("autogenerated_theme_id", (string?)prefs["extensions"]!["theme"]!["id"]);
        Assert.Equal(unchecked((int)0xFFDB2777), (int)prefs["autogenerated"]!["theme"]!["color"]!);
        Assert.Equal(BrowserPreviewAppearance.ThemeVersion, Assert.Single(Store.List()).Metadata!.ThemeVersion);
        Assert.Equal(profile.Key, Assert.Single(Store.List()).Key);
        Assert.Equal("Pink · #DB2777", new BrowserPreviewAppearance(null, "#db2777").ColorLabel);
    }

    [Fact]
    public void MalformedPreferencesAreNotOverwritten()
    {
        var profile = Create();
        Directory.CreateDirectory(Path.Combine(profile.Path, "Default"));
        var file = Path.Combine(profile.Path, "Default", "Preferences");
        File.WriteAllText(file, "broken");
        Assert.ThrowsAny<System.Text.Json.JsonException>(() => Store.SaveAppearance(profile, new(null, "#FF0000"), _ => false));
        Assert.Equal("broken", File.ReadAllText(file));
    }

    public void Dispose() { if (Directory.Exists(_root)) Directory.Delete(_root, true); }
}
