using System.Globalization;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

namespace HostsManager.Core;

public sealed record BrowserPreviewAppearance(string? Name, string? Color)
{
    public const int ThemeVersion = 3;
    public static int ThemeVersionFor(string browser) => browser == "edge" ? 2 : ThemeVersion;
    public string ColorLabel => Normalize().Color switch
    {
        null => "Browser default", "#2563EB" => "Blue · #2563EB", "#16A34A" => "Green · #16A34A",
        "#EA580C" => "Orange · #EA580C", "#9333EA" => "Purple · #9333EA", "#DC2626" => "Red · #DC2626",
        "#0D9488" => "Teal · #0D9488", "#DB2777" => "Pink · #DB2777", var hex => hex
    };
    public BrowserPreviewAppearance Normalize()
    {
        var name = Name?.Trim();
        if (name?.Length > 80 || (name?.Any(char.IsControl) ?? false))
            throw new ArgumentException("Use a profile name of at most 80 characters without control characters.");
        var color = Color?.Trim();
        if (!string.IsNullOrEmpty(color) && !Regex.IsMatch(color, "\\A#[0-9a-fA-F]{6}\\z"))
            throw new ArgumentException("Choose a color or enter #RRGGBB, for example #2563EB.");
        return new(string.IsNullOrEmpty(name) ? null : name,
            string.IsNullOrEmpty(color) ? null : color.ToUpperInvariant());
    }

    // Chromium preferences are an internal compatibility boundary. Only app-owned,
    // inactive profiles may be patched. Keep all unrelated preference data intact.
    public string UpdatePreferences(string json, string browser)
    {
        var appearance = Normalize();
        if (browser is not ("chrome" or "edge")) throw new ArgumentException("Unsupported browser.");
        var root = JsonNode.Parse(json) as JsonObject ?? throw new ArgumentException("Invalid browser preferences.");
        var theme = Object(Object(root, "browser"), "theme");
        var extensionTheme = Object(Object(root, "extensions"), "theme");
        var generated = Object(Object(root, "autogenerated"), "theme");
        theme.Remove("user_color");
        theme.Remove("user_color2");
        theme.Remove("color_variant2");
        theme.Remove("grayscale_theme_enabled2");
        theme.Remove("is_grayscale");
        theme.Remove("is_grayscale2");
        theme.Remove("color_variant");
        theme.Remove("follows_system_colors");
        generated.Remove("color");
        extensionTheme.Remove("pack");
        extensionTheme["id"] = "";
        if (appearance.Color is { } hex)
        {
            var argb = unchecked((int)(0xFF000000u | uint.Parse(hex[1..], NumberStyles.HexNumber)));
            theme["is_grayscale2"] = false;
            theme["follows_system_colors"] = false;
            // Use the classic generated-theme path for both Chromium browsers.
            // The modern user_color2 path retained the seed but failed to display
            // the requested hue in the tested Chrome build.
            generated["color"] = argb;
            extensionTheme["id"] = "autogenerated_theme_id";
        }
        return root.ToJsonString();
    }

    private static JsonObject Object(JsonObject parent, string key)
    {
        if (parent[key] is JsonObject value) return value;
        if (parent[key] is not null) throw new ArgumentException("Invalid browser preference structure.");
        var created = new JsonObject();
        parent[key] = created;
        return created;
    }
}
